name: Newman Run

on:
  push:
    branches:
    - main
  schedule:
  - cron: "0 2 * * 1-5"
  
jobs:
  newman:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          collection: LibraryAPI.postman_collection.json
          environment: qa.postman_environment.json
